export const STRINGS = {
  appTitle: "Price Compare",
  appSubtitle: "AI-powered product comparison across top Indian stores",

  chatPlaceholder: "Ask me to find a product...",
  chatSendLabel: "Send",
  chatEmptyHeading: "What are you looking for?",
  chatEmptySubtext: "Try one of these to get started:",
  chatExamplePrompts: [
    "Compare Nandini cow milk prices",
    "Find Aashirvaad Atta 5kg",
    "Best Tata Salt 1kg deals on Amazon",
  ],

  typingIndicatorLabel: "Searching...",
  viewResultsChip: "View full comparison",
  assistantName: "PriceBot",

  picksHeading: "Picks for you",
  picksRefresh: "Refresh picks",
  picksEmpty: "No picks yet — start a search above.",
  picksError: "Couldn't load your picks right now.",

  flipkartFallbackMessage:
    "I couldn't find that in our catalog, so I'm searching Flipkart for live results…",

  tableIdleHeading: "Ready when you are",
  tableIdleSubtext: "Ask the assistant about a product and comparisons will show up here.",
  tableEmptyHeading: "No products found",
  tableEmptySubtext: "Try a different search term or broaden your query.",
  tableLoadingLabel: "Loading results...",
  tableErrorHeading: "Something went wrong",
  tableErrorSubtext: "We couldn't fetch products. Please try again.",

  columnName: "Product",
  columnSource: "Store",
  columnCurrentPrice: "Price",
  columnLastPaid: "Last Paid",
  columnTrend: "Trend",
  columnRating: "Rating",
  columnAvailability: "Availability",
  columnWeight: "Weight",
  columnLastOrdered: "Last Ordered",
  columnSuggestion: "Buy?",
  columnLink: "Link",

  topMatchBadge: "Top match",
  liveResultBadge: "New",
  liveResultTooltip: "Fetched live from the store website",
  viewButtonLabel: "View",
  noRankLabel: "—",

  suggestionFrequent: "Frequent buy",
  suggestionRestock: "Time to restock",
  suggestionRecent: "Recently bought",
  suggestionNew: "New to you",

  recommendationsButton: "Recommendations",
  recommendationsTitle: "Next Purchase",
  recommendationsSubtitle: "Smart picks based on your buying habits",
  recommendationsInputLabel: "Preference (optional)",
  recommendationsInputPlaceholder: "e.g. only from Flipkart",
  recommendationsDefaultInput: "Give recommendations",
  recommendationsSubmit: "Get recommendations",
  recommendationsInsightLabel: "Insight",
  recommendationsLoading: "Finding your next purchase…",
  recommendationsEmptyHeading: "No recommendations yet",
  recommendationsEmptySubtext: "Add a preference or just get our top picks.",
  recommendationsErrorHeading: "Couldn't load recommendations",
  recommendationsClose: "Close recommendations",
  recommendationsRatingUnavailable: "Not available",

  cartButton: "Cart",
  cartTitle: "Your Cart",
  cartSubtitle: "Review items, then submit your order",
  cartClose: "Close cart",
  cartEmptyHeading: "Your cart is empty",
  cartEmptySubtext: "Add products from the comparison table or recommendations.",
  addToCart: "Add",
  addedToCart: "Added",
  removeFromCart: "Remove from cart",
  cartSubmit: "Submit Order",
  cartSubmitting: "Submitting…",
  cartSubmitError: "Couldn't submit your order",

  refreshAmazon: "Refresh Amazon",
  refreshFlipkart: "Refresh Flipkart",
  refreshing: "Refreshing…",
  enterAmazonOtp: "Enter Amazon OTP",
  refreshAmazonSuccess: "Amazon refresh completed. Click 'Enter Amazon OTP' if you need to submit an OTP.",
  refreshFlipkartSuccess: "Flipkart refresh started. Updated data will appear shortly.",
  refreshError: "Couldn't start the refresh. Please try again.",

  otpTitle: "Enter OTP",
  otpSubtitle: "Amazon sent a one-time code to complete the refresh.",
  otpPlaceholder: "6-digit code",
  otpSubmit: "Submit OTP",
  otpSubmitting: "Submitting…",
  otpCancel: "Cancel",
  otpClose: "Close OTP dialog",
  otpSuccess: "OTP submitted.",
  otpError: "Couldn't submit the OTP. Please try again.",

  menuLabel: "More options",
  installApp: "Install app",
  installInstalled: "App installed",
  installHint:
    'To install, open your browser menu and choose "Install app" / "Add to Home screen".',
} as const;
