export const STRINGS = {
  appTitle: "Price Compare",
  appSubtitle: "AI-powered product comparison across top Indian stores",

  chatPlaceholder: "Ask me to find a product...",
  chatSendLabel: "Send",
  chatEmptyHeading: "What are you looking for?",
  chatEmptySubtext: "Try one of these to get started:",
  chatExamplePrompts: [
    "Compare Nandini cow milk prices",
    "Find Aashirvaad Atta 5kg",
    "Best Tata Salt 1kg deals on Amazon",
  ],

  typingIndicatorLabel: "Searching...",
  assistantName: "PriceBot",

  tableEmptyHeading: "No products found",
  tableEmptySubtext: "Try a different search term or broaden your query.",
  tableLoadingLabel: "Loading results...",
  tableErrorHeading: "Something went wrong",
  tableErrorSubtext: "We couldn't fetch products. Please try again.",

  columnName: "Product",
  columnSource: "Store",
  columnCurrentPrice: "Price",
  columnRating: "Rating",
  columnAvailability: "Availability",
  columnLastOrdered: "Last Ordered",
  columnSuggestion: "Buy?",
  columnLink: "Link",

  topMatchBadge: "Top match",
  viewButtonLabel: "View",
  noRankLabel: "—",

  suggestionFrequent: "Frequent buy",
  suggestionRestock: "Time to restock",
  suggestionRecent: "Recently bought",
  suggestionNew: "New to you",

  recommendationsButton: "Recommendations",
  recommendationsTitle: "Next Purchase",
  recommendationsSubtitle: "Smart picks based on your buying habits",
  recommendationsInputLabel: "Preference (optional)",
  recommendationsInputPlaceholder: "e.g. only from Flipkart",
  recommendationsDefaultInput: "Give recommendations",
  recommendationsSubmit: "Get recommendations",
  recommendationsInsightLabel: "Insight",
  recommendationsLoading: "Finding your next purchase…",
  recommendationsEmptyHeading: "No recommendations yet",
  recommendationsEmptySubtext: "Add a preference or just get our top picks.",
  recommendationsErrorHeading: "Couldn't load recommendations",
  recommendationsClose: "Close recommendations",
  recommendationsRatingUnavailable: "Not available",
} as const;
